project:
  type: website
  preview:
    navigate: false
    port: 3000

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    keep-md: true
  commonmark: default

website:
  favicon: favicon.ico
  open-graph: true
  repo-actions: [issue]
  navbar:
    title: false
    logo: "logo.svg"
    background: primary
    search: true
    left:
      - text: "Home"
        href: https://pla.sh
      - text: "Learn"
        href: https://docs.pla.sh
    right:
      - icon: github
        href: "https://github.com/answerdotai/plash_cli"
      - icon: twitter
        href: https://x.com/answerdotai
        aria-label: Answer.ai Twitter
  sidebar:
    style: floating
    contents:
      - text: "Get Started"
        href: index.ipynb
      - section: "How To"
        contents: how_to/*
      - section: Explanations
        contents: explains/*
      - section: Reference
        contents: reference/*

metadata-files: [nbdev.yml]